name = "cloudflare-docs-product-firewall"
type = "webpack"

route = "https://cloudflare-docs-testing.ruthless.design/firewall*"
account_id = "1e1395dd88464c726799aac6c1be4a71"
zone_id = "e2c9f69be50a2b6870060b418cecffc7"
workers_dev = false

[site]
bucket = ".docs/public/firewall"
entry-point = ".docs/workers-site"
