name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: products/terraform
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - run: |
          npm install
          mkdir .docs
          npm run bootstrap
          npm run build
          npm i @cloudflare/wrangler@1.4.0-rc.7 -g
      - run: wrangler publish
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}

  deploy-spectrum:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: products/spectrum
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - run: |
          npm install
          mkdir .docs
          npm run bootstrap
          npm run build
          npm i @cloudflare/wrangler@1.4.0-rc.7 -g
      - run: wrangler publish
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
